#!/usr/bin/env python3
import json
from sys import argv

if len(argv)!=3:
    print(f"Usage: {argv[0]} input-file output-file")
    exit()

f = open(argv[1], 'r') #input.ipynb
j = json.load(f)
of = open(argv[2], 'w') #output.py
if j["nbformat"] >=4:
    for i,cell in enumerate(j["cells"]):
        of.write("#cell "+str(i)+"\n")
        for line in cell["source"]:
            of.write(line)
        of.write('\n\n')
else:
    for i,cell in enumerate(j["worksheets"][0]["cells"]):
        of.write("#cell "+str(i)+"\n")
        for line in cell["input"]:
            of.write(line)
        of.write('\n\n')

of.close()
